# Server Configuration
server:
  port: 8080
spring:
  application:
    name: GatewayRentakar
  # Gateway Configuration
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:8082"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 5000
        wiretap: true
      httpserver:
        wiretap: true
      routes:
        - id: USERRENTAKAR
          uri: lb://USERRENTAKAR
          predicates:
            - Path=/users/**

        - id: VEHICULERENTAKAR
          uri: lb://VEHICULERENTAKAR
          predicates:
            - Path=/vehicules/**

        - id: ORDERRENTAKAR
          uri: lb://ORDERRENTAKAR
          predicates:
            - Path=/orders/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  main:
    web-application-type: reactive

  # Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9097/eureka/
  instance:
    preferIpAddress: true

